"""add is_favorite column

Revision ID: 1738f58453a9
Revises: 71b2786d9ec9
Create Date: 2026-03-17 06:08:51.619308
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1738f58453a9'
down_revision: Union[str, None] = '71b2786d9ec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.add_column('chat_sessions', sa.Column('is_favorite', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_interaction_logs_timestamp'), 'interaction_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_interaction_logs_user_level'), 'interaction_logs', ['user_level'], unique=False)
    op.drop_column('user_profiles', 'consecutive_high')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('consecutive_high', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_interaction_logs_user_level'), table_name='interaction_logs')
    op.drop_index(op.f('ix_interaction_logs_timestamp'), table_name='interaction_logs')
    op.drop_column('chat_sessions', 'is_favorite')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    # ### end Alembic commands ###
